on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hey!! Nice job on your hackpad submission. This is alexren // @qcoral sending this automation to let you know that the submission guidelines have been updated, please follow https://hackpad.hackclub.com/submitting again. Sorry for the confusion!! Hopefully this won't be needed again.